---
namespace: rsoliman
name: openshift_virt_demos
version: 1.0.0
readme: README.md
authors:
  - Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo Openshift virtualization automation using Ansible.

license:
  - MIT

tags: [Openshift, Virtualization, demo, ansible, raedrizk, rsoliman]
dependencies:
  redhat.openshift_virtualization: "*"
  redhat.openshift: "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
